# Model Performance Transformations

Lets practice some basic data transformation for ML performance enhancement

In [1]:
# Imports
#%pip install duckdb
#%pip install sqlite
import pandas as pd
import numpy as np 
import sys
import re
sys.path.insert(0, "modules")

import numpy as np
import pandas as pd


import seaborn as sns

from sklearn.model_selection import GridSearchCV
import pickle
import numpy as np
import pandas as pd
from sklearn.preprocessing import RobustScaler, StandardScaler
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import SGDClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn import linear_model
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import Ridge
from sklearn.svm import SVR
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression

In [39]:
diamonds_test= pd.read_csv('../data/diamonds_test_data/diamonds_test.csv')

In [63]:
from functions import cat_var,delete_features_corr, remove_outliers, remove_outliers_price, drop_zeros, remove_duplicates, imputation, label_encoder, onehot_encoder, inverse_scaler, feature_ing, robust_scaling_train, stardard_scaling_train, robust_scaling_test, standard_scaling_test,calculate_log

ImportError: cannot import name 'calculate_log' from 'functions' (C:\Users\Veronica\M3\Project_M3_competition\notebook\functions.py)

In [41]:
diamonds_test

,id,carat,cut,color,clarity,depth,table,x,y,z,city
0,0,0.79,Very Good,F,SI1,62.7,60.0,5.82,5.89,3.67,Amsterdam
1,1,1.20,Ideal,J,VS1,61.0,57.0,6.81,6.89,4.18,Surat
2,2,1.57,Premium,H,SI1,62.2,61.0,7.38,7.32,4.57,Kimberly
3,3,0.90,Very Good,F,SI1,63.8,54.0,6.09,6.13,3.90,Kimberly
4,4,0.50,Very Good,F,VS1,62.9,58.0,5.05,5.09,3.19,Amsterdam
...,...,...,...,...,...,...,...,...,...,...,...
13480,13480,0.57,Ideal,E,SI1,61.9,56.0,5.35,5.32,3.30,Amsterdam
13481,13481,0.71,Ideal,I,VS2,62.2,55.0,5.71,5.73,3.56,New York City
13482,13482,0.70,Ideal,F,VS1,61.6,55.0,5.75,5.71,3.53,Tel Aviv
13483,13483,0.70,Very Good,F,SI2,58.8,57.0,5.85,5.89,3.45,Surat
13484,13484,0.40,Ideal,I,VVS2,62.4,55.0,4.70,4.73,2.94,New York City

## Transformations

---

In [42]:
diamonds_test = diamonds_test.drop(columns=['city','id'])

In [44]:
nuevo_orden_columnas = ['cut', 'color', 'clarity', 'carat', 'depth', 'table', 'x', 'y', 'z']

diamonds_test = diamonds_test[nuevo_orden_columnas]

In [46]:
diamonds_test=imputation(diamonds_test)

In [47]:
trans_df=diamonds_test
trans_df = calculate_log(trans_df, 'carat')
trans_df = calculate_log(trans_df, 'x')
trans_df = calculate_log(trans_df, 'y')
trans_df = calculate_log(trans_df, 'z')
trans_df['ratio_length_width'] = trans_df['x']/trans_df['y']
trans_df['ratio_length_width_depth'] = trans_df['x']/trans_df['y']/trans_df['z']
trans_df['volume'] = trans_df['x']*trans_df['y']*trans_df['z']
trans_df['density'] = trans_df['carat']/trans_df['volume']
diamonds_test=trans_df

In [48]:
#diamonds_test=feature_ing(diamonds_test)

In [49]:
diamonds_test.isnull().sum()

cut                         0
color                       0
clarity                     0
carat                       0
depth                       0
table                       0
x                           0
y                           0
z                           0
log_carat                   0
log_x                       0
log_y                       0
log_z                       0
ratio_length_width          0
ratio_length_width_depth    0
volume                      0
density                     0
dtype: int64

In [50]:
diamonds_test

,cut,color,clarity,carat,depth,table,x,y,z,log_carat,log_x,log_y,log_z,ratio_length_width,ratio_length_width_depth,volume,density
0,Very Good,F,SI1,0.79,62.7,60.0,5.82,5.89,3.67,-0.235722,1.761300,1.773256,1.300192,0.988115,0.269241,125.806866,0.006279
1,Ideal,J,VS1,1.20,61.0,57.0,6.81,6.89,4.18,0.182322,1.918392,1.930071,1.430311,0.988389,0.236457,196.129362,0.006118
2,Premium,H,SI1,1.57,62.2,61.0,7.38,7.32,4.57,0.451076,1.998774,1.990610,1.519513,1.008197,0.220612,246.878712,0.006359
3,Very Good,F,SI1,0.90,63.8,54.0,6.09,6.13,3.90,-0.105361,1.806648,1.813195,1.360977,0.993475,0.254737,145.593630,0.006182
4,Very Good,F,VS1,0.50,62.9,58.0,5.05,5.09,3.19,-0.693147,1.619388,1.627278,1.160021,0.992141,0.311016,81.997355,0.006098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,Ideal,E,SI1,0.57,61.9,56.0,5.35,5.32,3.30,-0.562119,1.677097,1.671473,1.193922,1.005639,0.304739,93.924600,0.006069
13481,Ideal,I,VS2,0.71,62.2,55.0,5.71,5.73,3.56,-0.342490,1.742219,1.745716,1.269761,0.996510,0.279918,116.477148,0.006096
13482,Ideal,F,VS1,0.70,61.6,55.0,5.75,5.71,3.53,-0.356675,1.749200,1.742219,1.261298,1.007005,0.285271,115.898725,0.006040
13483,Very Good,F,SI2,0.70,58.8,57.0,5.85,5.89,3.45,-0.356675,1.766442,1.773256,1.238374,0.993209,0.287887,118.874925,0.005889
13484,Ideal,I,VVS2,0.40,62.4,55.0,4.70,4.73,2.94,-0.916291,1.547563,1.553925,1.078410,0.993658,0.337979,65.359140,0.006120

In [211]:
diamonds_test=diamonds_test.fillna(0)

## Enconding

ML algorithms do not support categorical data. Therefore you need to find a way to transform categorical data into numerical. You must compare the results using both techniques: __One Hot Encoding__ or __Label Encoding__

- [OneHotEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html#sklearn.preprocessing.OneHotEncoder)

- [LabelEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder)

<img src="../images/encoding.png" alt="Drawing" style="width: 500px;"/>

In [212]:
#diamonds_test=onehot_encoder(diamonds_test)

In [51]:
diamonds_test =label_encoder(diamonds_test)

In [52]:
diamonds_test

,cut,color,clarity,carat,depth,table,x,y,z,log_carat,log_x,log_y,log_z,ratio_length_width,ratio_length_width_depth,volume,density
0,4,2,2,0.79,62.7,60.0,5.82,5.89,3.67,-0.235722,1.761300,1.773256,1.300192,0.988115,0.269241,125.806866,0.006279
1,2,6,4,1.20,61.0,57.0,6.81,6.89,4.18,0.182322,1.918392,1.930071,1.430311,0.988389,0.236457,196.129362,0.006118
2,3,4,2,1.57,62.2,61.0,7.38,7.32,4.57,0.451076,1.998774,1.990610,1.519513,1.008197,0.220612,246.878712,0.006359
3,4,2,2,0.90,63.8,54.0,6.09,6.13,3.90,-0.105361,1.806648,1.813195,1.360977,0.993475,0.254737,145.593630,0.006182
4,4,2,4,0.50,62.9,58.0,5.05,5.09,3.19,-0.693147,1.619388,1.627278,1.160021,0.992141,0.311016,81.997355,0.006098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,2,1,2,0.57,61.9,56.0,5.35,5.32,3.30,-0.562119,1.677097,1.671473,1.193922,1.005639,0.304739,93.924600,0.006069
13481,2,5,5,0.71,62.2,55.0,5.71,5.73,3.56,-0.342490,1.742219,1.745716,1.269761,0.996510,0.279918,116.477148,0.006096
13482,2,2,4,0.70,61.6,55.0,5.75,5.71,3.53,-0.356675,1.749200,1.742219,1.261298,1.007005,0.285271,115.898725,0.006040
13483,4,2,3,0.70,58.8,57.0,5.85,5.89,3.45,-0.356675,1.766442,1.773256,1.238374,0.993209,0.287887,118.874925,0.005889
13484,2,5,7,0.40,62.4,55.0,4.70,4.73,2.94,-0.916291,1.547563,1.553925,1.078410,0.993658,0.337979,65.359140,0.006120

## Scaling

In [53]:
#diamonds_test=stardard_scaling_test(diamonds_test)

In [55]:
diamonds_test=robust_scaling_test(diamonds_test)

In [56]:
diamonds_test

,cut,color,clarity,carat,depth,table,x,y,z,log_carat,log_x,log_y,log_z,ratio_length_width,ratio_length_width_depth,volume,density
0,2.0,-0.333333,-0.666667,0.140625,0.533333,1.000000,0.066667,0.094444,0.125000,0.126584,0.064605,0.090818,0.119798,-0.535111,-0.145559,0.101500,1.144410
1,0.0,1.000000,0.000000,0.781250,-0.600000,0.000000,0.616667,0.650000,0.580357,0.564092,0.551740,0.577094,0.520584,-0.516017,-0.493776,0.770425,0.006196
2,1.0,0.333333,-0.666667,1.359375,0.200000,1.333333,0.933333,0.888889,0.928571,0.845359,0.800999,0.764823,0.795338,0.866783,-0.662069,1.253165,1.709303
3,2.0,-0.333333,-0.666667,0.312500,1.266667,-1.000000,0.216667,0.227778,0.330357,0.263016,0.205227,0.214666,0.307024,-0.160976,-0.299613,0.289716,0.452690
4,2.0,-0.333333,0.000000,-0.312500,0.666667,0.333333,-0.361111,-0.350000,-0.303571,-0.352138,-0.375457,-0.361853,-0.311947,-0.254052,0.298148,-0.315227,-0.139764
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,0.0,-0.666667,-0.666667,-0.203125,0.000000,-0.333333,-0.194444,-0.222222,-0.205357,-0.215009,-0.196506,-0.224805,-0.207525,0.688232,0.231478,-0.201772,-0.345137
13481,0.0,0.666667,0.333333,0.015625,0.200000,-0.666667,0.005556,0.005556,0.026786,0.014845,0.005435,0.005417,0.026066,0.050893,-0.032152,0.012753,-0.154898
13482,0.0,-0.333333,0.000000,0.000000,-0.200000,-0.666667,0.027778,-0.005556,0.000000,0.000000,0.027083,-0.005426,0.000000,0.783605,0.024695,0.007251,-0.549675
13483,2.0,-0.333333,-0.333333,0.000000,-2.066667,0.000000,0.083333,0.094444,-0.071429,0.000000,0.080549,0.090818,-0.070608,-0.179537,0.052481,0.035561,-1.618334
13484,0.0,0.666667,1.000000,-0.468750,0.333333,-0.666667,-0.555556,-0.550000,-0.526786,-0.585671,-0.598185,-0.589316,-0.563321,-0.148215,0.584528,-0.473494,0.017650

## Model

In [58]:
filename = '../models/Gradientboosting_001.sav'
model = pickle.load(open(filename, 'rb'))

In [59]:

predictions=model.predict(diamonds_test)

In [61]:
df_predictions = pd.DataFrame(predictions, columns=['price'], index=range(len(predictions)))
df_predictions = df_predictions.rename_axis('id')
df_predictions

             price
id
0      2928.514980
1      5662.128332
2      9668.874141
3      4022.162805
4      1600.004624
...            ...
13480  1657.228646
13481  2405.559082
13482  3002.630650
13483  2139.231097
13484   769.142289

[13485 rows x 1 columns]

In [62]:
df_predictions.to_csv('../data/submission/003.csv')